/*
 * This file is generated by jOOQ.
 */
package mv.local.tables


import java.util.function.Function

import mv.local.Cars
import mv.local.keys.CAR_IMAGES_PKEY
import mv.local.tables.records.CarImagesRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CarImages(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, CarImagesRecord>?,
    aliased: Table<CarImagesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<CarImagesRecord>(
    alias,
    Cars.CARS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>cars.car_images</code>
         */
        val CAR_IMAGES: CarImages = CarImages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CarImagesRecord> = CarImagesRecord::class.java

    /**
     * The column <code>cars.car_images.id</code>.
     */
    val ID: TableField<CarImagesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>cars.car_images.car_cards_id</code>.
     */
    val CAR_CARDS_ID: TableField<CarImagesRecord, Int?> = createField(DSL.name("car_cards_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>cars.car_images.link</code>.
     */
    val LINK: TableField<CarImagesRecord, String?> = createField(DSL.name("link"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<CarImagesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<CarImagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>cars.car_images</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>cars.car_images</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>cars.car_images</code> table reference
     */
    constructor(): this(DSL.name("car_images"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, CarImagesRecord>): this(Internal.createPathAlias(child, key), child, key, CAR_IMAGES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Cars.CARS
    override fun getIdentity(): Identity<CarImagesRecord, Long?> = super.getIdentity() as Identity<CarImagesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CarImagesRecord> = CAR_IMAGES_PKEY
    override fun `as`(alias: String): CarImages = CarImages(DSL.name(alias), this)
    override fun `as`(alias: Name): CarImages = CarImages(alias, this)
    override fun `as`(alias: Table<*>): CarImages = CarImages(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CarImages = CarImages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CarImages = CarImages(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CarImages = CarImages(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Long?, Int?, String?> = super.fieldsRow() as Row3<Long?, Int?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Int?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Int?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
