/*
 * This file is generated by jOOQ.
 */
package mv.local.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CarImages(
    var id: Long? = null,
    var carCardsId: Int? = null,
    var link: String? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("CarImages (")

        sb.append(id)
        sb.append(", ").append(carCardsId)
        sb.append(", ").append(link)

        sb.append(")")
        return sb.toString()
    }
}
