/*
 * This file is generated by jOOQ.
 */
package mv.local.tables.references


import mv.local.tables.CarCards
import mv.local.tables.CarImages
import mv.local.tables.StaticText



/**
 * The table <code>cars.car_cards</code>.
 */
val CAR_CARDS: CarCards = CarCards.CAR_CARDS

/**
 * The table <code>cars.car_images</code>.
 */
val CAR_IMAGES: CarImages = CarImages.CAR_IMAGES

/**
 * The table <code>cars.static_text</code>.
 */
val STATIC_TEXT: StaticText = StaticText.STATIC_TEXT
