/*
 * This file is generated by jOOQ.
 */
package mv.local.tables.records


import mv.local.tables.Brand

import org.jooq.Field
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BrandRecord() : TableRecordImpl<BrandRecord>(Brand.BRAND), Record3<Long?, String?, String?> {

    open var carCardsId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var carName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var link: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Long?, String?, String?> = super.fieldsRow() as Row3<Long?, String?, String?>
    override fun valuesRow(): Row3<Long?, String?, String?> = super.valuesRow() as Row3<Long?, String?, String?>
    override fun field1(): Field<Long?> = Brand.BRAND.CAR_CARDS_ID
    override fun field2(): Field<String?> = Brand.BRAND.CAR_NAME
    override fun field3(): Field<String?> = Brand.BRAND.LINK
    override fun component1(): Long? = carCardsId
    override fun component2(): String? = carName
    override fun component3(): String? = link
    override fun value1(): Long? = carCardsId
    override fun value2(): String? = carName
    override fun value3(): String? = link

    override fun value1(value: Long?): BrandRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): BrandRecord {
        set(1, value)
        return this
    }

    override fun value3(value: String?): BrandRecord {
        set(2, value)
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: String?): BrandRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised BrandRecord
     */
    constructor(carCardsId: Long? = null, carName: String? = null, link: String? = null): this() {
        this.carCardsId = carCardsId
        this.carName = carName
        this.link = link
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised BrandRecord
     */
    constructor(value: mv.local.tables.pojos.Brand?): this() {
        if (value != null) {
            this.carCardsId = value.carCardsId
            this.carName = value.carName
            this.link = value.link
            resetChangedOnNotNull()
        }
    }
}
