/*
 * This file is generated by jOOQ.
 */
package mv.local.tables.records


import mv.local.tables.CarImages

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CarImagesRecord() : TableRecordImpl<CarImagesRecord>(CarImages.CAR_IMAGES), Record2<Long?, String?> {

    open var carCardsId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var link: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Long?, String?> = super.fieldsRow() as Row2<Long?, String?>
    override fun valuesRow(): Row2<Long?, String?> = super.valuesRow() as Row2<Long?, String?>
    override fun field1(): Field<Long?> = CarImages.CAR_IMAGES.CAR_CARDS_ID
    override fun field2(): Field<String?> = CarImages.CAR_IMAGES.LINK
    override fun component1(): Long? = carCardsId
    override fun component2(): String? = link
    override fun value1(): Long? = carCardsId
    override fun value2(): String? = link

    override fun value1(value: Long?): CarImagesRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): CarImagesRecord {
        set(1, value)
        return this
    }

    override fun values(value1: Long?, value2: String?): CarImagesRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised CarImagesRecord
     */
    constructor(carCardsId: Long? = null, link: String? = null): this() {
        this.carCardsId = carCardsId
        this.link = link
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CarImagesRecord
     */
    constructor(value: mv.local.tables.pojos.CarImages?): this() {
        if (value != null) {
            this.carCardsId = value.carCardsId
            this.link = value.link
            resetChangedOnNotNull()
        }
    }
}
