/*
 * This file is generated by jOOQ.
 */
package mv.local


import kotlin.collections.List

import mv.local.tables.CarCards
import mv.local.tables.CarImages
import mv.local.tables.StaticText

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Cars : SchemaImpl("cars", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>cars</code>
         */
        val CARS: Cars = Cars()
    }

    /**
     * The table <code>cars.car_cards</code>.
     */
    val CAR_CARDS: CarCards get() = CarCards.CAR_CARDS

    /**
     * The table <code>cars.car_images</code>.
     */
    val CAR_IMAGES: CarImages get() = CarImages.CAR_IMAGES

    /**
     * The table <code>cars.static_text</code>.
     */
    val STATIC_TEXT: StaticText get() = StaticText.STATIC_TEXT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        CarCards.CAR_CARDS,
        CarImages.CAR_IMAGES,
        StaticText.STATIC_TEXT
    )
}
