/*
 * This file is generated by jOOQ.
 */
package mv.local.keys


import mv.local.tables.Brand
import mv.local.tables.CarCards
import mv.local.tables.CarImages
import mv.local.tables.StaticText
import mv.local.tables.records.BrandRecord
import mv.local.tables.records.CarCardsRecord
import mv.local.tables.records.CarImagesRecord
import mv.local.tables.records.StaticTextRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CAR_CARDS_PKEY: UniqueKey<CarCardsRecord> = Internal.createUniqueKey(CarCards.CAR_CARDS, DSL.name("car_cards_pkey"), arrayOf(CarCards.CAR_CARDS.ID), true)
val STATIC_TEXT_PKEY: UniqueKey<StaticTextRecord> = Internal.createUniqueKey(StaticText.STATIC_TEXT, DSL.name("static_text_pkey"), arrayOf(StaticText.STATIC_TEXT.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BRAND__BRAND_CAR_CARDS_ID_FKEY: ForeignKey<BrandRecord, CarCardsRecord> = Internal.createForeignKey(Brand.BRAND, DSL.name("brand_car_cards_id_fkey"), arrayOf(Brand.BRAND.CAR_CARDS_ID), mv.local.keys.CAR_CARDS_PKEY, arrayOf(CarCards.CAR_CARDS.ID), true)
val CAR_IMAGES__CAR_IMAGES_CAR_CARDS_ID_FKEY: ForeignKey<CarImagesRecord, CarCardsRecord> = Internal.createForeignKey(CarImages.CAR_IMAGES, DSL.name("car_images_car_cards_id_fkey"), arrayOf(CarImages.CAR_IMAGES.CAR_CARDS_ID), mv.local.keys.CAR_CARDS_PKEY, arrayOf(CarCards.CAR_CARDS.ID), true)
