/*
 * This file is generated by jOOQ.
 */
package mv.local.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class CarCards(
    var id: Long? = null,
    var owner: String? = null,
    var carMileage: Int? = null,
    var carYear: Int? = null,
    var cost: Int? = null,
    var carCondition: String? = null,
    var carEngine: Double? = null,
    var description: String? = null,
    var transmission: String? = null
): Serializable {


    override fun toString(): String {
        val sb = StringBuilder("CarCards (")

        sb.append(id)
        sb.append(", ").append(owner)
        sb.append(", ").append(carMileage)
        sb.append(", ").append(carYear)
        sb.append(", ").append(cost)
        sb.append(", ").append(carCondition)
        sb.append(", ").append(carEngine)
        sb.append(", ").append(description)
        sb.append(", ").append(transmission)

        sb.append(")")
        return sb.toString()
    }
}
